import { countryMeta as geoCountryMeta } from './geo-resolve.mjs';
import { chainStageForSite } from './value-chain.mjs';

/**
 * Rare-earth and critical mineral mining / processing sites with map coordinates.
 * Sources: company disclosures, USGS/Mindat public coordinates (rounded).
 */

/** @typedef {'operating' | 'development' | 'processing' | 'deposit' | 'historic'} SiteStatus */

/** @typedef {{
 *   id: string,
 *   name: string,
 *   aliases?: string[],
 *   lat: number,
 *   lon: number,
 *   countryCode: string,
 *   countryName: string,
 *   flag: string,
 *   status: SiteStatus,
 *   operators: string[],
 *   elements: string[],
 *   notes?: string,
 * }} MiningSite */

/** @type {MiningSite[]} */
export const MINING_SITES = [
  {
    id: 'mountain-pass',
    name: 'Mountain Pass',
    lat: 35.484,
    lon: -115.526,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'operating',
    operators: ['MP'],
    elements: ['Nd', 'Pr', 'Ce', 'La'],
    notes: 'Only scaled REE mine in the U.S.',
  },
  {
    id: 'white-mesa',
    name: 'White Mesa Mill',
    lat: 37.45,
    lon: -109.55,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'processing',
    operators: ['UUUU'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb', 'U'],
    notes: 'Conventional mill; REE separation ramp-up',
  },
  {
    id: 'round-top',
    name: 'Round Top',
    lat: 30.133,
    lon: -105.217,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'development',
    operators: ['USAR', 'TMRC'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb', 'Y'],
  },
  {
    id: 'bear-lodge',
    name: 'Bear Lodge',
    lat: 44.52,
    lon: -104.18,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'development',
    operators: ['REEMF'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'stillwater-ree',
    name: 'Stillwater REE plant',
    lat: 36.115,
    lon: -96.998,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'development',
    operators: ['USAR'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'mt-weld',
    name: 'Mt Weld',
    lat: -28.865,
    lon: 122.193,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'operating',
    operators: ['LYC'],
    elements: ['Nd', 'Pr', 'La', 'Ce', 'Dy', 'Tb'],
    notes: 'Concentrate feed for Malaysia and Kalgoorlie processing',
  },
  {
    id: 'kalgoorlie-ree',
    name: 'Kalgoorlie Rare Earths Processing Facility',
    lat: -30.75,
    lon: 121.47,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'operating',
    operators: ['LYC'],
    elements: ['Nd', 'Pr'],
  },
  {
    id: 'lynas-malaysia',
    name: 'Lynas Malaysia (LAMP)',
    lat: 4.322,
    lon: 103.428,
    countryCode: 'MY',
    countryName: 'Malaysia',
    flag: '🇲🇾',
    status: 'processing',
    operators: ['LYC'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb', 'La', 'Ce'],
  },
  {
    id: 'yangibana',
    name: 'Yangibana',
    lat: -23.58,
    lon: 120.12,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'development',
    operators: ['HAS'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'ngualla',
    name: 'Ngualla',
    lat: -8.25,
    lon: 33.85,
    countryCode: 'TZ',
    countryName: 'Tanzania',
    flag: '🇹🇿',
    status: 'deposit',
    operators: ['PEK'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
    notes: 'Peak Rare Earths flagship deposit',
  },
  {
    id: 'nolans',
    name: 'Nolans Bore',
    lat: -22.55,
    lon: 133.42,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'development',
    operators: ['ARU'],
    elements: ['Nd', 'Pr', 'Ce', 'La'],
    aliases: ['Nolans', 'Nolans Project', 'Nolans Neodymium-Praseodymium'],
  },
  {
    id: 'songwe',
    name: 'Songwe Hill',
    lat: -15.68,
    lon: 35.58,
    countryCode: 'MW',
    countryName: 'Malawi',
    flag: '🇲🇼',
    status: 'development',
    operators: ['MKA'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'bayan-obo',
    name: 'Bayan Obo',
    lat: 41.77,
    lon: 109.95,
    countryCode: 'CN',
    countryName: 'China',
    flag: '🇨🇳',
    status: 'operating',
    operators: ['CN-state'],
    elements: ['La', 'Ce', 'Nd', 'Pr', 'Sm', 'Eu', 'Gd', 'Dy', 'Tb'],
    notes: 'World’s largest REE mine by volume',
  },
  {
    id: 'southern-ionics',
    name: 'South China ionic clay belt',
    lat: 25.5,
    lon: 114.5,
    countryCode: 'CN',
    countryName: 'China',
    flag: '🇨🇳',
    status: 'operating',
    operators: ['CN-state'],
    elements: ['Dy', 'Tb', 'Y', 'Er', 'Ho'],
    notes: 'Heavy REE ionic adsorption clays',
  },
  {
    id: 'mountain-weld-cn',
    name: 'Myanmar ionic clays (export)',
    lat: 21.9,
    lon: 100.1,
    countryCode: 'MM',
    countryName: 'Myanmar',
    flag: '🇲🇲',
    status: 'operating',
    operators: ['CN-refiners'],
    elements: ['Dy', 'Tb', 'Y'],
    notes: 'Heavy REE feedstock to China',
  },
  {
    id: 'eneabba',
    name: 'Eneabba REE refinery',
    lat: -29.82,
    lon: 115.27,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'processing',
    operators: ['ILU'],
    elements: ['La', 'Ce', 'Nd', 'Pr'],
  },
  {
    id: 'steenkampskraal',
    name: 'Steenkampskraal',
    lat: -32.25,
    lon: 18.35,
    countryCode: 'ZA',
    countryName: 'South Africa',
    flag: '🇿🇦',
    status: 'deposit',
    operators: ['private'],
    elements: ['Nd', 'Pr', 'La', 'Ce'],
  },
  {
    id: 'kvanefjeld',
    name: 'Kvanefjeld',
    lat: 60.95,
    lon: -45.38,
    countryCode: 'GL',
    countryName: 'Greenland',
    flag: '🇬🇱',
    status: 'deposit',
    operators: ['GML'],
    elements: ['La', 'Ce', 'Nd', 'Pr'],
    aliases: ['Kvanefjeld Project'],
  },
  {
    id: 'dubbo',
    name: 'Dubbo Project',
    aliases: ['Dubbo', 'Dubbo rare earths'],
    lat: -32.45,
    lon: 148.72,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'development',
    operators: ['ASM'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb', 'Zr', 'Nb'],
  },
  {
    id: 'makuutu',
    name: 'Makuutu',
    aliases: ['Makuutu Rare Earths Project'],
    lat: 0.65,
    lon: 33.55,
    countryCode: 'UG',
    countryName: 'Uganda',
    flag: '🇺🇬',
    status: 'development',
    operators: ['IXR'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb', 'Y'],
  },
  {
    id: 'nechalacho',
    name: 'Nechalacho',
    aliases: ['Nechalacho Project', 'Tardiff'],
    lat: 62.28,
    lon: -112.65,
    countryCode: 'CA',
    countryName: 'Canada',
    flag: '🇨🇦',
    status: 'development',
    operators: ['VML'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
    notes: 'Tardiff deposit; among largest Western REE systems',
  },
  {
    id: 'brockman',
    name: 'Brockman',
    aliases: ['Brockman Project', 'Brockman heavy rare earths'],
    lat: -17.2,
    lon: 125.8,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'deposit',
    operators: ['HAS'],
    elements: ['Dy', 'Tb', 'Y', 'Nd', 'Pr'],
  },
  {
    id: 'sierra-rutile',
    name: 'Sierra Rutile',
    lat: 7.55,
    lon: -12.45,
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    flag: '🇸🇱',
    status: 'operating',
    operators: ['ILU'],
    elements: ['La', 'Ce', 'Nd', 'Pr', 'Zr'],
    notes: 'Mineral sands; REE in tailings streams',
  },
  {
    id: 'browns-range',
    name: 'Browns Range',
    lat: -18.85,
    lon: 127.95,
    countryCode: 'AU',
    countryName: 'Australia',
    flag: '🇦🇺',
    status: 'development',
    operators: ['NTU'],
    elements: ['Dy', 'Tb', 'Y'],
    notes: 'Northern Minerals HREE pilot',
  },
  {
    id: 'mount-weld-cn-alt',
    name: 'Maoniuping',
    aliases: ['Maoniuping rare earth mine'],
    lat: 26.58,
    lon: 101.72,
    countryCode: 'CN',
    countryName: 'China',
    flag: '🇨🇳',
    status: 'operating',
    operators: ['CN-state'],
    elements: ['La', 'Ce', 'Nd', 'Pr'],
    notes: 'Sichuan light REE',
  },
  {
    id: 'mianning',
    name: 'Mianning',
    lat: 28.55,
    lon: 102.18,
    countryCode: 'CN',
    countryName: 'China',
    flag: '🇨🇳',
    status: 'operating',
    operators: ['CN-state'],
    elements: ['La', 'Ce', 'Nd', 'Pr'],
  },
  {
    id: 'dong-pao',
    name: 'Dong Pao',
    lat: 22.35,
    lon: 104.65,
    countryCode: 'VN',
    countryName: 'Vietnam',
    flag: '🇻🇳',
    status: 'development',
    operators: ['private'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'strange-lake',
    name: 'Strange Lake',
    lat: 56.33,
    lon: -64.15,
    countryCode: 'CA',
    countryName: 'Canada',
    flag: '🇨🇦',
    status: 'deposit',
    operators: ['QCC'],
    elements: ['Dy', 'Tb', 'Y', 'Nd', 'Pr'],
  },
  {
    id: 'lovozero',
    name: 'Lovozero',
    lat: 68.0,
    lon: 35.7,
    countryCode: 'RU',
    countryName: 'Russia',
    flag: '🇷🇺',
    status: 'operating',
    operators: ['RU-state'],
    elements: ['La', 'Ce', 'Nd', 'Pr', 'Eu'],
  },
  {
    id: 'tomtor',
    name: 'Tomtor',
    lat: 67.0,
    lon: 147.5,
    countryCode: 'RU',
    countryName: 'Russia',
    flag: '🇷🇺',
    status: 'deposit',
    operators: ['RU-state'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb', 'Y'],
  },
  {
    id: 'araxa',
    name: 'Araxá',
    aliases: ['Araxa'],
    lat: -19.58,
    lon: -46.95,
    countryCode: 'BR',
    countryName: 'Brazil',
    flag: '🇧🇷',
    status: 'operating',
    operators: ['CBMM'],
    elements: ['Nb', 'La', 'Ce'],
    notes: 'Niobium mine with REE by-product',
  },
  {
    id: 'goias',
    name: 'Serra Verde',
    aliases: ['Serra Verde Project'],
    lat: -14.2,
    lon: -47.5,
    countryCode: 'BR',
    countryName: 'Brazil',
    flag: '🇧🇷',
    status: 'development',
    operators: ['private'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'longonjo',
    name: 'Longonjo',
    lat: -12.55,
    lon: 15.55,
    countryCode: 'AO',
    countryName: 'Angola',
    flag: '🇦🇴',
    status: 'development',
    operators: ['PEN'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'lofdal',
    name: 'Lofdal',
    lat: -20.45,
    lon: 14.85,
    countryCode: 'NA',
    countryName: 'Namibia',
    flag: '🇳🇦',
    status: 'deposit',
    operators: ['private'],
    elements: ['Dy', 'Tb', 'Y'],
  },
  {
    id: 'norra-karr',
    name: 'Norra Kärr',
    aliases: ['Norra Karr'],
    lat: 57.82,
    lon: 14.28,
    countryCode: 'SE',
    countryName: 'Sweden',
    flag: '🇸🇪',
    status: 'deposit',
    operators: ['private'],
    elements: ['Dy', 'Tb', 'Y', 'Nd', 'Pr'],
  },
  {
    id: 'halleck-creek',
    name: 'Halleck Creek',
    lat: 41.05,
    lon: -104.95,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'deposit',
    operators: ['AREC'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'bokan',
    name: 'Bokan Mountain',
    aliases: ['Bokan', 'Bokan-Dotson Ridge'],
    lat: 54.85,
    lon: -132.82,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'deposit',
    operators: ['UCU', 'UURAF'],
    elements: ['Dy', 'Tb', 'Y', 'Nd', 'Pr'],
  },
  {
    id: 'strathmore',
    name: 'Church Rock',
    aliases: ['Church Rock', 'Crownpoint'],
    lat: 35.68,
    lon: -108.35,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'historic',
    operators: ['UUUU'],
    elements: ['Nd', 'Pr', 'U'],
    notes: 'Legacy Navajo Nation uranium/REE district',
  },
  {
    id: 'phosphate-florida',
    name: 'Florida phosphate REE',
    lat: 27.65,
    lon: -81.8,
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    status: 'processing',
    operators: ['UUUU', 'MP'],
    elements: ['Ce', 'La', 'Nd', 'Pr'],
    notes: 'Monazite from phosphate mining',
  },
  {
    id: 'saskatchewan-ree',
    name: 'Saskatchewan REE belt',
    aliases: ['Saskatchewan', 'Nechalacho-style clays'],
    lat: 54.5,
    lon: -106.0,
    countryCode: 'CA',
    countryName: 'Canada',
    flag: '🇨🇦',
    status: 'deposit',
    operators: ['private'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'madagascar-tantalus',
    name: 'Tantalus REE',
    lat: -16.2,
    lon: 47.8,
    countryCode: 'MG',
    countryName: 'Madagascar',
    flag: '🇲🇬',
    status: 'deposit',
    operators: ['private'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
  {
    id: 'india-chavara',
    name: 'Chavara',
    lat: 8.95,
    lon: 76.55,
    countryCode: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    status: 'operating',
    operators: ['IN-state'],
    elements: ['La', 'Ce', 'Nd', 'Pr'],
    notes: 'Indian Rare Earths mineral sands',
  },
  {
    id: 'malaysia-lynas-alt',
    name: 'Gebeng',
    aliases: ['LAMP', 'Lynas Advanced Materials Plant'],
    lat: 4.322,
    lon: 103.428,
    countryCode: 'MY',
    countryName: 'Malaysia',
    flag: '🇲🇾',
    status: 'processing',
    operators: ['LYC'],
    elements: ['Nd', 'Pr', 'Dy', 'Tb'],
  },
];

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const SITE_NAME_PATTERNS = MINING_SITES.flatMap((s) => {
  const labels = [s.name, ...(s.aliases ?? [])];
  return labels.map((label) => ({
    site: s,
    re: new RegExp(`\\b${escapeRegExp(label)}\\b`, 'gi'),
  }));
});

/** Link filing text mentions to known sites. */
export function sitesMentionedInText(text) {
  const hits = [];
  for (const { site, re } of SITE_NAME_PATTERNS) {
    re.lastIndex = 0;
    if (re.test(text)) hits.push(site.id);
  }
  return [...new Set(hits)];
}

export function buildMiningSitesIndex(
  filingRows = [],
  { mrdsSites = [], strategicProjectSites = [] } = {},
) {
  const mentionCounts = Object.fromEntries(MINING_SITES.map((s) => [s.id, 0]));

  for (const row of filingRows) {
    const parts = [
      ...Object.values(row.elementHits ?? {}).flatMap((h) => h.snippets ?? []),
      ...(row.generalSnippets ?? []),
    ];
    for (const id of sitesMentionedInText(parts.join(' '))) {
      mentionCounts[id] = (mentionCounts[id] ?? 0) + 1;
    }
  }

  const curated = MINING_SITES.map((s) => ({
    ...s,
    source: s.source ?? 'curated',
    chainStage: chainStageForSite(s),
    secMentions: mentionCounts[s.id] ?? 0,
  }));

  const mrds = (mrdsSites ?? []).map((s) => ({
    ...s,
    source: 'USGS-MRDS',
    chainStage: chainStageForSite(s),
    secMentions: 0,
  }));

  const strategic = (strategicProjectSites ?? []).map((s) => ({
    ...s,
    source: 'EU-CRMA-strategic',
    chainStage: chainStageForSite(s),
    secMentions: 0,
  }));

  const sites = [...curated, ...strategic, ...mrds];

  const byCountry = {};
  for (const site of sites) {
    if (!byCountry[site.countryCode]) {
      byCountry[site.countryCode] = {
        ...geoCountryMeta(site.countryCode),
        sites: [],
      };
    }
    byCountry[site.countryCode].sites.push(site);
  }

  return {
    sites,
    byCountry: Object.values(byCountry).sort((a, b) => b.sites.length - a.sites.length),
    summary: {
      siteCount: sites.length,
      curatedCount: curated.length,
      strategicCount: strategic.length,
      mrdsCount: mrds.length,
      operating: sites.filter((s) => s.status === 'operating').length,
      countries: Object.keys(byCountry).length,
    },
  };
}
