/** Map MRDS / report country names → ISO 3166-1 alpha-2. */
export const COUNTRY_NAME_TO_CODE = {
  'United States': 'US',
  USA: 'US',
  China: 'CN',
  Australia: 'AU',
  Canada: 'CA',
  Brazil: 'BR',
  Russia: 'RU',
  'Russian Federation': 'RU',
  India: 'IN',
  Vietnam: 'VN',
  Malaysia: 'MY',
  Myanmar: 'MM',
  Burma: 'MM',
  Thailand: 'TH',
  Tanzania: 'TZ',
  Madagascar: 'MG',
  Namibia: 'NA',
  'South Africa': 'ZA',
  Greenland: 'GL',
  Sweden: 'SE',
  Norway: 'NO',
  Finland: 'FI',
  Malawi: 'MW',
  Uganda: 'UG',
  Angola: 'AO',
  Mongolia: 'MN',
  Kazakhstan: 'KZ',
  Indonesia: 'ID',
  Philippines: 'PH',
  Japan: 'JP',
  'South Korea': 'KR',
  'Korea, South': 'KR',
  'Korea, North': 'KP',
  'United Kingdom': 'GB',
  France: 'FR',
  Germany: 'DE',
  Spain: 'ES',
  Italy: 'IT',
  Poland: 'PL',
  Turkey: 'TR',
  Egypt: 'EG',
  Morocco: 'MA',
  Nigeria: 'NG',
  Mali: 'ML',
  Kenya: 'KE',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
  Mexico: 'MX',
  Chile: 'CL',
  Argentina: 'AR',
  Peru: 'PE',
  Bolivia: 'BO',
  Colombia: 'CO',
  Venezuela: 'VE',
  'New Zealand': 'NZ',
  'Papua New Guinea': 'PG',
  'Sierra Leone': 'SL',
  'Sri Lanka': 'LK',
  Iran: 'IR',
  Pakistan: 'PK',
  Afghanistan: 'AF',
  Nepal: 'NP',
  Laos: 'LA',
  Cambodia: 'KH',
  Taiwan: 'TW',
  'Hong Kong': 'HK',
  'Czech Republic': 'CZ',
  Slovakia: 'SK',
  Ukraine: 'UA',
  Belarus: 'BY',
  Georgia: 'GE',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
  Uzbekistan: 'UZ',
  Kyrgyzstan: 'KG',
  Tajikistan: 'TJ',
  Turkmenistan: 'TM',
  'Saudi Arabia': 'SA',
  Oman: 'OM',
  Yemen: 'YE',
  Jordan: 'JO',
  Israel: 'IL',
  Syria: 'SY',
  Iraq: 'IQ',
  Libya: 'LY',
  Tunisia: 'TN',
  Algeria: 'DZ',
  Ghana: 'GH',
  Senegal: 'SN',
  Cameroon: 'CM',
  Gabon: 'GA',
  Congo: 'CG',
  'Democratic Republic of the Congo': 'CD',
  DRC: 'CD',
  Burundi: 'BI',
  Rwanda: 'RW',
  Ethiopia: 'ET',
  Sudan: 'SD',
  'South Sudan': 'SS',
  Mozambique: 'MZ',
  Botswana: 'BW',
  Lesotho: 'LS',
  Eswatini: 'SZ',
  Swaziland: 'SZ',
};

export function countryNameToCode(name) {
  if (!name) return null;
  const trimmed = String(name).trim();
  if (COUNTRY_NAME_TO_CODE[trimmed]) return COUNTRY_NAME_TO_CODE[trimmed];
  const lower = trimmed.toLowerCase();
  for (const [k, v] of Object.entries(COUNTRY_NAME_TO_CODE)) {
    if (k.toLowerCase() === lower) return v;
  }
  return null;
}
