/**
 * Known semiconductor supply-chain entities for entity linking and tier assignment.
 */
export const VENDOR_ALIASES = {
  nvidia: 'Nvidia',
  'nvidia corporation': 'Nvidia',
  'nvidia corp': 'Nvidia',
  'taiwan semiconductor': 'TSMC',
  'taiwan semiconductor manufacturing': 'TSMC',
  'taiwan semiconductor manufacturing company limited': 'TSMC',
  tsmc: 'TSMC',
  tsm: 'TSMC',
  'sk hynix': 'SK Hynix',
  'sk hynix inc': 'SK Hynix',
  'sk hynix inc.': 'SK Hynix',
  'samsung electronics': 'Samsung',
  'samsung electronics co., ltd.': 'Samsung',
  samsung: 'Samsung',
  'micron technology': 'Micron',
  'micron technology, inc.': 'Micron',
  micron: 'Micron',
  'asml holding': 'ASML',
  'asml holding n.v.': 'ASML',
  asml: 'ASML',
  'applied materials': 'Applied Materials',
  'applied materials, inc.': 'Applied Materials',
  'lam research': 'Lam Research',
  'lam research corporation': 'Lam Research',
  'kla corporation': 'KLA',
  'kla-tencor corporation': 'KLA',
  kla: 'KLA',
  'tokyo electron': 'Tokyo Electron',
  'tokyo electron, ltd.': 'Tokyo Electron',
  'hitachi high-technologies corporation': 'Hitachi High-Tech',
  'hitachi, ltd.': 'Hitachi High-Tech',
  'hitachi high-tech': 'Hitachi High-Tech',
  'onto innovation': 'Onto Innovation',
  'onto innovation, inc.': 'Onto Innovation',
  'asm international': 'ASM International',
  'wonik ips': 'Wonik IPS',
  lasertec: 'Lasertec',
  synopsys: 'Synopsys',
  'synopsys, inc.': 'Synopsys',
  'cadence design systems': 'Cadence',
  'cadence design systems, inc.': 'Cadence',
  cadence: 'Cadence',
  'siemens eda': 'Siemens EDA',
  ansys: 'Ansys',
  'ansys, inc.': 'Ansys',
  'arm holdings': 'Arm',
  'arm limited': 'Arm',
  arm: 'Arm',
  'carl zeiss smt': 'Zeiss',
  'carl zeiss smt holding gmbh & co. kg': 'Zeiss',
  'carl zeiss smt gmbh': 'Zeiss',
  zeiss: 'Zeiss',
  cymer: 'Cymer',
  trumpf: 'Trumpf',
  'vat group': 'VAT Group',
  vat: 'VAT Group',
  toto: 'TOTO',
  'jsr corporation': 'JSR',
  jsr: 'JSR',
  'shin-etsu chemical': 'Shin-Etsu (Wafers)',
  'shin-etsu': 'Shin-Etsu (Wafers)',
  'linde plc': 'Linde',
  linde: 'Linde',
  ibiden: 'Ibiden',
  'hon hai precision industry': 'Hon Hai (Foxconn)',
  'hon hai precision industry co., ltd.': 'Hon Hai (Foxconn)',
  foxconn: 'Hon Hai (Foxconn)',
  'hon hai': 'Hon Hai (Foxconn)',
  wistron: 'Wistron',
  'wistron corporation': 'Wistron',
  fabrinet: 'Fabrinet',
  ase: 'ASE Technology',
  'ase technology': 'ASE Technology',
  'ase technology holding co., ltd.': 'ASE Technology',
  nikon: 'Nikon',
  'nikon corporation': 'Nikon',
  canon: 'Canon',
  'canon inc.': 'Canon',
  schott: 'Schott',
  hoya: 'Hoya',
  corning: 'Corning',
  'corning incorporated': 'Corning',
  'pfeiffer vacuum': 'Pfeiffer Vacuum',
  ferrotec: 'Ferrotec',
  'ipg photonics': 'IPG Photonics',
  intel: 'Intel',
  globalfoundries: 'GlobalFoundries',
  'globalfoundries inc': 'GlobalFoundries',
  gfs: 'GlobalFoundries',
  amkor: 'Amkor',
  'amkor technology': 'Amkor',
  'amkor technology, inc.': 'Amkor',
  umc: 'UMC',
  coherent: 'Trumpf',
  'edwards vacuum': 'VAT Group',
};

export const VENDOR_TIERS = {
  Nvidia: { tier: 0, group: 'product' },
  'Nvidia H200': { tier: 0, group: 'product' },
  'AMD MI325X': { tier: 0, group: 'product' },
  'Intel Gaudi 3': { tier: 0, group: 'product' },
  'AWS Trainium 2': { tier: 0, group: 'product' },
  'AWS Inferentia 2': { tier: 0, group: 'product' },
  'Microsoft Maia 100': { tier: 0, group: 'product' },
  'Google TPU v5p': { tier: 0, group: 'product' },
  'Nvidia B200': { tier: 0, group: 'product' },
  'AMD MI350X': { tier: 0, group: 'product' },
  'Intel Falcon Shores': { tier: 0, group: 'product' },
  'AWS Trainium 3': { tier: 0, group: 'product' },
  'Google TPU v6': { tier: 0, group: 'product' },
  'Huawei Ascend 910C': { tier: 0, group: 'product' },
  'Meta MTIA v2': { tier: 0, group: 'product' },
  'Microsoft Maia 200': { tier: 0, group: 'product' },
  'Baidu Kunlun 2': { tier: 0, group: 'product' },
  'SambaNova SN40': { tier: 0, group: 'product' },
  'Tenstorrent Blackhole': { tier: 0, group: 'product' },
  'Groq LPU': { tier: 0, group: 'product' },
  'Cerebras WSE-3': { tier: 0, group: 'product' },
  Intel: { tier: 1, group: 'foundry' },
  TSMC: { tier: 1, group: 'foundry' },
  GlobalFoundries: { tier: 1, group: 'foundry' },
  Samsung: { tier: 1, group: 'memory' },
  'SK Hynix': { tier: 1, group: 'memory' },
  Micron: { tier: 1, group: 'memory' },
  'Hon Hai (Foxconn)': { tier: 1, group: 'osat' },
  Wistron: { tier: 1, group: 'osat' },
  Fabrinet: { tier: 1, group: 'osat' },
  Amkor: { tier: 1, group: 'osat' },
  'ASE Technology': { tier: 1, group: 'osat' },
  Synopsys: { tier: 1, group: 'eda' },
  Cadence: { tier: 1, group: 'eda' },
  'Siemens EDA': { tier: 1, group: 'eda' },
  Ansys: { tier: 1, group: 'eda' },
  Arm: { tier: 1, group: 'eda' },
  ASML: { tier: 2, group: 'equipment' },
  'Applied Materials': { tier: 2, group: 'equipment' },
  'Lam Research': { tier: 2, group: 'equipment' },
  KLA: { tier: 2, group: 'equipment' },
  'Tokyo Electron': { tier: 2, group: 'equipment' },
  'Hitachi High-Tech': { tier: 2, group: 'equipment' },
  'Onto Innovation': { tier: 2, group: 'equipment' },
  'ASM International': { tier: 2, group: 'equipment' },
  'Wonik IPS': { tier: 2, group: 'equipment' },
  Lasertec: { tier: 2, group: 'equipment' },
  Nikon: { tier: 2, group: 'equipment' },
  Canon: { tier: 2, group: 'equipment' },
  JSR: { tier: 2, group: 'materials' },
  'Shin-Etsu (PR)': { tier: 2, group: 'materials' },
  'Shin-Etsu (Wafers)': { tier: 2, group: 'materials' },
  Linde: { tier: 2, group: 'materials' },
  Ibiden: { tier: 2, group: 'materials' },
  Zeiss: { tier: 3, group: 'subcomponent' },
  Cymer: { tier: 3, group: 'subcomponent' },
  Trumpf: { tier: 3, group: 'subcomponent' },
  'VAT Group': { tier: 3, group: 'subcomponent' },
  TOTO: { tier: 3, group: 'subcomponent' },
  Schott: { tier: 4, group: 'raw' },
  Hoya: { tier: 4, group: 'raw' },
  Corning: { tier: 4, group: 'raw' },
  'Pfeiffer Vacuum': { tier: 4, group: 'raw' },
  Ferrotec: { tier: 4, group: 'raw' },
  'IPG Photonics': { tier: 4, group: 'raw' },
};

export const SUPPLY_CHAIN_QUERIES = [
  'suppliers vendors subcontractors single source sole supplier',
  'Taiwan Semiconductor TSMC foundry CoWoS packaging',
  'SK Hynix Samsung Micron HBM memory purchase',
  'Hon Hai Wistron Fabrinet assembly testing packaging',
  'Carl Zeiss SMT sole supplier optics EUV',
  'ASML lithography EUV Cymer light source',
  'Applied Materials Lam Research KLA Tokyo Electron',
  'Hitachi Onto Innovation ASM International Wonik',
  'Synopsys Cadence Siemens EDA Ansys Arm',
  'substrate interposer Ibiden photoresist gases',
  'customer concentration revenue dependency',
];

export function canonicalize(name) {
  const key = name.toLowerCase().replace(/\s+/g, ' ').trim();
  if (VENDOR_ALIASES[key]) return VENDOR_ALIASES[key];
  // Partial match for Carl Zeiss variants
  if (/carl zeiss/i.test(name)) return 'Zeiss';
  if (/hon hai|foxconn/i.test(name)) return 'Hon Hai (Foxconn)';
  return name.trim();
}

export const SANKEY_ALLOWLIST = new Set([
  'Nvidia H200',
  'AMD MI325X',
  'Intel Gaudi 3',
  'AWS Trainium 2',
  'AWS Inferentia 2',
  'Microsoft Maia 100',
  'Google TPU v5p',
  'Nvidia B200',
  'AMD MI350X',
  'Intel Falcon Shores',
  'AWS Trainium 3',
  'Google TPU v6',
  'Huawei Ascend 910C',
  'Meta MTIA v2',
  'Microsoft Maia 200',
  'Baidu Kunlun 2',
  'SambaNova SN40',
  'Tenstorrent Blackhole',
  'Groq LPU',
  'Cerebras WSE-3',
  ...Object.keys(VENDOR_TIERS),
  ...new Set(Object.values(VENDOR_ALIASES)),
]);

export function isKnownVendor(name) {
  const c = canonicalize(name);
  return SANKEY_ALLOWLIST.has(c) || VENDOR_TIERS[c] != null;
}
